apiVersion: v2
name: apocalypse
description: A Helm chart for Apocalypse Spring Boot application
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - spring-boot
  - java
  - apocalypse
maintainers:
  - name: ByteRevo
    email: support@byterevo.com
